import re

# Auto-generated from JavaScript eventTypeMatchers
EVENT_TYPE_MATCHERS = {
    'Retraction': [
        re.compile('\\bRetractions?\\b', re.IGNORECASE),
        re.compile('\\bnot\\s+a\\s+(?:GRB|GW|FRB|SN|SGR|neutrino)\\b', re.IGNORECASE),
        re.compile('\\bprobably\\s+not\\s+a\\b', re.IGNORECASE),
        re.compile('\\bis\\s+not\\b', re.IGNORECASE),
        re.compile('\\bDisregard\\b', re.IGNORECASE),
        re.compile('\\bIgnore\\b', re.IGNORECASE),
        re.compile('\\bFalse Trigger\\b', re.IGNORECASE),
        re.compile('\\bNot real\\b', re.IGNORECASE),
        re.compile('\\bErroneous\\b', re.IGNORECASE),
        re.compile('\\bDuplicate\\b', re.IGNORECASE),
    ],
    'GRB': [
        re.compile('\\bGRB\\d{6}[A-Z]?\\b', re.IGNORECASE),
        re.compile('\\bGRBs?\\b', re.IGNORECASE),
        re.compile('\\bgamma[-\\s]?ray[-\\s]?bursts?\\b', re.IGNORECASE),
        re.compile('\\bXRF\\d{6}[A-Z]?\\b', re.IGNORECASE),
    ],
    'Gamma-ray Transient': [
        re.compile('\\bFermi(?:\\s?(?:GBM|LAT)|\\d{9})?\\b', re.IGNORECASE),
        re.compile('\\bSwift(?!\\s?[:?/-]?(?:XRT|UVOT))\\b', re.IGNORECASE),
        re.compile('\\bSwift[:?/-]BAT\\b', re.IGNORECASE),
        re.compile('\\bSVOM\\(?!\\/VT|\\/C-GFT\\)\\b', re.IGNORECASE),
        re.compile('\\bINTEGRAL\\b', re.IGNORECASE),
        re.compile('\\bHETE\\b', re.IGNORECASE),
        re.compile('\\bKONUS\\b', re.IGNORECASE),
        re.compile('\\bAstroSat\\b', re.IGNORECASE),
        re.compile('\\bHAWC(-\\d{6}[A-Za-z])?:?$\\b', re.IGNORECASE),
    ],
    'GW': [
        re.compile('\\bGW\\d+\\b', re.IGNORECASE),
        re.compile('\\bGWs?\\b', re.IGNORECASE),
        re.compile('\\bgravitational[-\\s]?waves?\\b', re.IGNORECASE),
        re.compile('\\bLIGO\\b', re.IGNORECASE),
        re.compile('\\bVirgo\\b', re.IGNORECASE),
        re.compile('\\bKAGRA\\b', re.IGNORECASE),
        re.compile('\\bS\\d{6}[a-z]+\\b', re.IGNORECASE),
        re.compile('\\bGWTC-\\d+\\b', re.IGNORECASE),
    ],
    'SGR': [
        re.compile('\\bSGR\\S*', re.IGNORECASE),
        re.compile('\\bsoft[-\\s]?gamma[-\\s]?repeaters?\\b', re.IGNORECASE),
    ],
    'FRB': [
        re.compile('\\bFRB\\s?\\d{6,8}[A-Za-z]?\\b', re.IGNORECASE),
        re.compile('\\bFRBs?\\b', re.IGNORECASE),
        re.compile('\\bfast[-\\s]?radio[-\\s]?bursts?\\b', re.IGNORECASE),
        re.compile('\\bCHIME\\b', re.IGNORECASE),
        re.compile('\\bDSA-110\\b', re.IGNORECASE),
    ],
    'SN': [
        re.compile('\\bSN\\d{4}[A-Za-z]*\\b', re.IGNORECASE),
        re.compile('\\bSNe?\\b', re.IGNORECASE),
        re.compile('\\bsuper[-\\s]?novae?\\b', re.IGNORECASE),
    ],
    'Nova': [
        re.compile('\\b(?<!super)nova(ae)?\\b', re.IGNORECASE),
    ],
    'Neutrino': [
        re.compile('\\bneutrinos?\\b', re.IGNORECASE),
        re.compile('\\bIceCube(?:-HAWC|-\\d+)?\\b', re.IGNORECASE),
        re.compile('\\bANTARES\\b', re.IGNORECASE),
        re.compile('\\bKM3NeT\\b', re.IGNORECASE),
        re.compile('\\bSuper-Kamiokande\\b', re.IGNORECASE),
        re.compile('\\bSNEWS2\\b', re.IGNORECASE),
    ],
    'X-ray Transient': [
        re.compile('(?<!\\S)EP(?=\\s|:|$)'),
        re.compile('\\bEPW?[-\\s]?\\d{6,8}[A-Z]{0,2}\\b', re.IGNORECASE),
        re.compile('\\bEP-WXT\\b', re.IGNORECASE),
        re.compile('\\bEP-FXT\\b', re.IGNORECASE),
        re.compile('\\bX[-\\s]?ray(?:\\s+transient)?\\b', re.IGNORECASE),
        re.compile('\\bEinstein\\s+Probe\\b', re.IGNORECASE),
        re.compile('\\bMAXI\\s?J\\d{4}[+-]\\d+', re.IGNORECASE),
        re.compile('\\bXRT\\b', re.IGNORECASE),
        re.compile('\\bXRF\\b', re.IGNORECASE),
        re.compile('\\bChandra\\b', re.IGNORECASE),
        re.compile('\\bXMM\\b', re.IGNORECASE),
        re.compile('\\bNICER\\b', re.IGNORECASE),
        re.compile('\\bNuSTAR\\b', re.IGNORECASE),
        re.compile('\\bSwift[:?/-]XRT\\b', re.IGNORECASE),
    ],
    'Afterglow': [
        re.compile('\\bafterglows?\\b', re.IGNORECASE),
        re.compile('\\bGW170817\\b', re.IGNORECASE),
    ],
    'Optical Transient': [
        re.compile('\\boptical\\b(?!\\s+upper\\s+limits?\\b)', re.IGNORECASE),
        re.compile('\\bOT\\b', re.IGNORECASE),
        re.compile('\\bAT\\d{4}[a-z]+\\b', re.IGNORECASE),
        re.compile('\\bHubble\\b', re.IGNORECASE),
        re.compile('\\bZTF(?:\\d{2}[A-Za-z0-9]+)?\\b', re.IGNORECASE),
        re.compile('\\bMASTER\\b', re.IGNORECASE),
        re.compile('\\bPan-STARRS\\b', re.IGNORECASE),
        re.compile('\\bRubin\\b', re.IGNORECASE),
        re.compile('\\bSVOM\\/VT\\b', re.IGNORECASE),
        re.compile('\\bSVOM\\/C-GFT\\b', re.IGNORECASE),
        re.compile('\\bSwift[:?/-]UVOT\\b', re.IGNORECASE),
    ],
    'Kilonova': [
        re.compile('\\bkilonovae?\\b(?!-\\w)', re.IGNORECASE),
        re.compile('\\bKN\\b', re.IGNORECASE),
        re.compile('\\bGW170817\\b', re.IGNORECASE),
        re.compile('\\bAT2017gfo\\b', re.IGNORECASE),
    ],
    'Misc': [
    ],
}
